alphagov/co-eu-transition-dashboard

package-lock.json
package.json

Adding release-it to dependencies to allow easier releases

add release functionality

---

deploy.sh
manifest.yml
package.json
production.yml
staging.yml

Seperate deployments between staging and production

Staging separation

---

config/production.json
config/staging.json
scripts/createUser.js

Use different fill values for the different environments

send different emails to different environments

---

config/default.json
config/development.json
config/production.json
config/staging.json
pages/authentication/Authentication.js

this allows users to have multiple 2fa tokens in their chosen app to login to staging and production

add environment names to 2fa name

---

services/authentication.js
test/unit/middleware/helmet.test.js

ensure cookies expiration get reset on each access

persist cookie on each access

---

app.js
package-lock.json
package.json
webpack.config.js

- Remove middleware when on production
- When deploying to a none development environment you must run `npm run build` before `npm start`

use middleware for dev only

---

migrations/00_user_login_attempts.js
models/user.js
package-lock.json
package.json
pages/authentication/partials/auth-error.njk
resources/database/setup.sql
server.js
services/authentication.js
services/sequelize.js
test/unit/models/user.test.js
test/unit/mysql-mock.js
test/unit/services/authentication.test.js

- block user if bad login
- fixed up unit tests for services/authentication
- add MySQL database migrations

block user if bad login

---

core/pages/page.js
pages/authentication/login/Login.js
pages/authentication/password-reset/PasswordReset.js
pages/authentication/password-reset/partials/password-reset-complete.njk
pages/authentication/password-reset/partials/password-reset.njk
services/sequelize.js
test/unit/pages/authentication/Login.test.js
test/unit/pages/authentication/PasswordReset.test.js

- Password reset page was not redirecting correctly
- add logs for database migration

fix password reset, add database migration logs

---

pages/authentication/two-factor-authentication/partials/register.njk
pages/authentication/two-factor-authentication/partials/setup.njk
pages/authentication/two-factor-authentication/partials/verify.njk

- Sophie has requested some updates to the text displayed on the login screens

text-changes

---

migrations/02_field_entries.js
models/milestoneFieldEntry.js
models/projectFieldEntry.js

Convert binary blobs to text in the field entry tables.

Field entry format

---

webpack.config.js

Fix build for environments other than dev

fix assets for prod

---

scripts/createUser.js
scripts/resetUser.js

Properly include privacy link which seems to have gotten lost in a branch

reset user properly with privacy link

---

common/javascript/upcoming-milestones.js
models/user.js
pages/upcoming-milestones/UpcomingMilestones.html

- update title
- remove min,max dates
- update sort function

upcoming milestones updates

---

models/milestone.js
models/project.js
pages/admin/import/Import.js
test/unit/models/milestone.test.js

- allow null for impact and date ( milestones )

Fix issues with latest date import

---

common/javascript/upcoming-milestones.js
pages/upcoming-milestones/UpcomingMilestones.html
pages/upcoming-milestones/UpcomingMilestones.scss

minor change to update way chart height is calculated

fix sizing of chart

---

models/user.js

do not include all milestone associations as this causes sequelise to get stuck in loop

fix get single roject data

---

deploy.sh
readme.md

Updated changes for deployment using gitlabs flow

Flow deployment

---

app.js
common/views/template.njk
config/default.json
config/development.json
config/research.json
config/staging.json
core/pages/page.js
helpers/startPage.js
pages/authentication/login/Login.js
pages/authentication/password-reset/PasswordReset.js
pages/authentication/two-factor-authentication/TwoFactorAuthentication.js
pages/index.js
pages/missed-milestones/MissedMilestones.js
pages/start/Start.js
pages/upcoming-milestones/UpcomingMilestones.html
test/unit/core/pages/page.test.js
test/unit/pages/MissedMilestones.test.js
test/unit/pages/Start.test.js
test/unit/pages/authentication/Login.test.js
test/unit/pages/authentication/PasswordReset.test.js
test/unit/pages/authentication/TwoFactorAuthentication.test.js
test/unit/pages/index.test.js

- add new start page ( used to redirect from the root )
- hide missed milestones behind feature toggle
- hide upcoming milestone chart behind a feature toggle

Hide milestones features behind feature toggle

---

common/javascript/main.js
common/javascript/remove-accordion-cross.js
pages/all-data/AllData.html
pages/all-data/AllData.scss
pages/authentication/login/Login.js
pages/authentication/password-reset/partials/password-reset-complete.njk
test/unit/pages/authentication/Login.test.js

- change lock typo 
- prevent double click of finish button
- projects to not display plus sign if no milestones, if none of the projects have milestones on the page then the open all button does not appear

Ui bug fixes

---

pages/all-data/AllData.scss

To put all milestones date to black

remove css red date

---

common/javascript/remove-accordion-cross.js
pages/all-data/AllData.html

Placed JS code onto AllData page as it was causing a bug raised by Sophie on the project details page

accordion-bug-fix

---

helpers/models.js
models/milestone.js
models/milestoneFieldEntry.js
models/projectFieldEntry.js
models/user.js
pages/missed-milestones/MissedMilestones.js

- speed up database queries
- only show none complete milestones in missed milestones

only show none complete milestones in missed milestones

---

config/default.json
helpers/utils.js
models/milestone.js
models/project.js
package-lock.json
package.json
pages/data-entry/bulk-upload/partials/bulk-upload.njk
pages/data-entry/import/Import.html
test/unit/helpers/utils.test.js
test/unit/models/milestone.test.js
test/unit/models/project.test.js

also, increase the timeout to 1 hour

auto assign ids for projects and milestones if no idea supplied also, increase the timeout to 1 hour

---

helpers/parse.js
pages/data-entry/project-milestone-template/ProjectMilestoneTemplate.js
test/unit/helpers/parse.test.js
test/unit/pages/data-entry/ProjectMilestoneTemplate.test.js

- rework drop down lists
- fix importing n/a values

fixes for export

---

pages/data-entry/bulk-upload/partials/upload-file.njk
pages/data-entry/import/Import.js
test/unit/pages/data-entry/Import.test.js

will also need to add a new milestone column in the database:
milstone field: 
```INSERT INTO `milestone_field` (`id`, `name`, `display_name`, `type`, `config`, `is_active`, `is_required`, `import_column_name`, `order`, `description`)
VALUES
(7, 'priorityTheme', 'Priority Theme', 'string', CONVERT(X'7B226578706F72744F7074696F6E73223A207B22686561646572223A207B2266696C6C223A2022464645353944227D2C20226465736372697074696F6E223A207B2266696C6C223A2022464646324345227D7D7D' using utf8mb4), 1, 0, 'Priority Theme', 7, NULL);```

fix export link, auto assign priority theme

---

helpers/filters.js
models/milestone.js
models/milestoneFieldEntry.js
pages/all-data/AllData.html
pages/all-data/AllData.js
pages/milestone-details/MilestoneDetails.html
pages/project-details/ProjectDetails.html
pages/project-details/ProjectDetails.js
pages/upcoming-milestones/UpcomingMilestones.js
pages/upcoming-milestones/partials/filters/filters.njk
test/unit/pages/UpcomingMilestones.test.js

- add extra milestone specific filters to upcoming milestones page
- add milestone status to all-data and project-details milestone table

Missed milestone filters milestone status

---

models/user.js
pages/authentication/login/Login.js
pages/authentication/password-reset/PasswordReset.js
pages/start/Start.js
scripts/resetUser.js
test/unit/models/user.test.js
test/unit/pages/Start.test.js
test/unit/pages/authentication/Login.test.js
test/unit/pages/authentication/PasswordReset.test.js

Update the user model to reference the correct column name in database

DDB-463 - change password on reset

---

config/custom-environment-variables.json
config/default.json
config/production.json
config/research.json
config/staging.json
package-lock.json
package.json
services/tableau.js
test/unit/services/tableau.test.js

Example of how to use inside page:
```
const tableau = require('services/tableau');
....
async getIframeUrl() {
return await tableau.getTableauUrl(this.req.user, 'workbook', 'view');
}
```
in HTML: 
```
<iframe src="{{ getIframeUrl() }}></iframe>
```

add tableau service to get iframe url

---

app.js
config/default.json
pages/page-not-found/PageNotFound.html
pages/page-not-found/PageNotFound.js
test/unit/pages/PageNotFound.test.js

When a user types in an address that doesn't exist, it will redirect to the 404 page

404-page bug fix

---

ci/pipeline.yml
readme.md

What
----
Add a deployment pipeline
Checklist
----
Screenshot
----
The [pipeline](https://cd.gds-reliability.engineering/teams/cabinet-office-transition/pipelines/co-eu-transition-dashboard)

deployment pipeline

---

common/scss/main.scss
common/views/navigation.njk
pages/all-data/AllData.scss

Navigation changes

---

common/views/template.njk
pages/admin/edit-project-field/EditProjectField.html
pages/authentication/login/Login.html
pages/authentication/password-reset/partials/password-reset-complete.njk
pages/authentication/two-factor-authentication/partials/register.njk
pages/authentication/two-factor-authentication/partials/setup.njk
pages/authentication/two-factor-authentication/partials/verified.njk
pages/privacy-notice/PrivacyNotice.html

Changing from Transition Delivery Dashboard to Transition Readiness Dashboard

Title changes

---

pages/readiness-overview/ReadinessOverview.js
pages/start/Start.js
test/unit/pages/Start.test.js

Missed this out in my previous branch

readiness-role

---

pages/global-partials/fields.njk

Remove dept editable field from the edit project page

remove edit dept from edit projects

---

migrations/14_category_next_id.js
models/category.js
models/entity.js
pages/data-entry/import/Import.js
test/unit/models/category.test.js
test/unit/models/entity.test.js
test/unit/pages/data-entry/Import.test.js

- Error on import if the theme is borders and user permissions do not include BPDG
- Fix auto-increment ID for entities

Bpdg borders only & fix auto ID

---

pages/tableau-export/TableauExport.js

do not include any active columns in export

fix comms exporting

---

common/views/navigation.njk
config/default.json
pages/theme/Theme.html
pages/theme/Theme.js
pages/theme/Theme.scss
test/unit/pages/Theme.test.js

this adds data for both left and middle columns of the theme data page

add data for theme page

---

common/views/navigation.njk
pages/data-entry-entity/category-template/CategoryTemplate.js
pages/data-entry-entity/entity-import/EntityImport.js
pages/theme/Theme.html
pages/theme/Theme.js
test/unit/pages/data-entry-entity/CategoryTemplate.test.js

- add theme details to print to the page
- fix errors with rag roll-ups
- fix errors with not being able to link to sub outcomes
- small performance tweaks

Theme detail pages, improvements and bug fixes

---

pages/readiness-overview/ReadinessOverview.html
pages/readiness-overview/ReadinessOverview.scss

Updated due date
Minor style change to improve appear when scrollbar appears
Upload links to use config path

Minor update to overview design

---

pages/theme/Theme.scss

fixed iframe size

---

package-lock.json
package.json
pages/data-entry-entity/entity-submission-success/EntitySubmissionSuccess.js
pages/theme/Theme.html
pages/theme/Theme.js
pages/theme/Theme.scss
services/nodeCache.js
services/tableau.js
test/unit/pages/data-entry-entity/EntitySubmissionSuccess.test.js
test/unit/services/tableau.test.js

- added iframe urls
- added new threshold 
- added cache to improve page load time

Theme page iframe urls

---

pages/readiness-overview/ReadinessOverview.html

Rearranged items in risk columns as requested
Fixed people link

Rearranged items in overview risk columns

---

common/javascript/readiness-accordion.js

Restores scroll position after page reload to provide a better user experience

Restore scroll position after page reload

---

pages/start/Start.js
test/unit/pages/Start.test.js

**New Requirement**
- Users will be redirected to the Readiness Overview page upon login
- If they do not have the role to view that page, they will be redirected to the Reporting Overview page
- They will have either or both

landing page update

---

common/javascript/main.js
common/javascript/readiness-accordion.js
common/javascript/readiness-scroll.js
pages/theme/Theme.html

Addressing previous PR comments.
Moved scroll logic out of accordion class and into a separate function to ensure event listener is only set once.
Added additional logic so scroll is only restored when on the same theme page, otherwise we clear the session

Theme page scroll update

---

pages/theme/Theme.html

prompt user to select measure if none selected

Theme detail no data message

---

common/views/navigation.njk
helpers/validation.js
middleware/entityUserPermissions.js
migrations/11_entity_tables.js
migrations/16_entity_upload_permissions.js
migrations/18_entity_upload_permissions.js
models/entityUser.js
models/user.js
pages/data-entry-entity/category-template/CategoryTemplate.js
pages/data-entry-entity/entity-import/EntityImport.html
pages/data-entry-entity/entity-import/EntityImport.js
test/unit/helpers/validation.test.js
test/unit/middleware/entityUserPermissions.test.js
test/unit/models/entityUser.test.js
test/unit/models/user.test.js
test/unit/pages/data-entry-entity/CategoryTemplate.test.js
test/unit/pages/data-entry-entity/EntityImport.test.js

- add a new table to link users to entities
- only allow export of entities to users with permissions to those entities
- only allow the import of entities to users with permissions to those entities
- allow admin to export/import all entites

entity user permissions

---

common/javascript/main.js
common/javascript/readiness-scroll.js
pages/theme/Theme.html

Leighs work on remembering the user's scroll position after page refresh - tested locally by me

Remember scroll position all columns

---

notifications/upcomingMilestones.js
test/unit/notifications/upcomingMilestones.test.js

Tested and working - only those with uploader role should get notifications

notification role fix

---

pages/all-data/AllData.html
pages/all-data/AllData.scss
pages/all-data/partials/filters/hide-filter-btn.njk
pages/all-data/partials/filters/show-filter-btn.njk
pages/upcoming-milestones/UpcomingMilestones.html

The filters on the All Data and Upcoming Milestones page will display by default

show filters by default

---

common/scss/main.scss
pages/missed-milestones/MissedMilestones.html
pages/missed-milestones/MissedMilestones.js
pages/missed-milestones/MissedMilestones.scss
test/unit/pages/MissedMilestones.test.js

Updates to the missed milestones page based on comments from Simon
- Ordering of the columns
- Width of some of the columns
- Ordering of dates

Missed milestones updates

---

common/macros/readiness-accordion.njk
pages/theme/Theme.scss

Display 'Comments Only' on measures with no graph

comments metric display

---

pages/theme/Theme.scss

Remove yellow background on focus

remove yellow background

---

common/views/navigation.njk
config/default.json
middleware/nunjucks.js
pages/admin/user-management/authentication/UserManagementAuthentication.html
pages/admin/user-management/authentication/UserManagementAuthentication.js
pages/admin/user-management/authentication/partials/reset.html
pages/admin/user-management/authentication/partials/success.html
pages/admin/user-management/list/UserManagementList.html
pages/admin/user-management/list/UserManagementList.js
test/unit/pages/admin/UserManagementAuthentication.test.js
test/unit/pages/admin/UserManagementList.test.js

Adds new admin pages to list users and allow admins reset user password

list users and reset password

---

pages/tableau-export-csv/TableauExportCsv.js
test/unit/pages/TableauExport.test.js
test/unit/pages/TableauExportCsv.test.js

Added export to Excel functionality for tableau export backup
Left export to CSV functionality to allow for flexibility in case there are any issues with Excel

Added export to Excel functionality for tableau export

---

common/javascript/tableau-wdc.js
helpers/transitionReadinessData.js
pages/authentication/two-factor-authentication/partials/verify.njk

- ensure WDC returns values unless they are undefined
- autofocus 2FA field
- Dont append a value to measures if its a comment only
- add new tableau link for comment only measures

tableau fixes

---

models/project.js

Update column name to match the template

Update column name to match template

---

test/unit/models/project.test.js

Updating test for import column name update

Updating test for import column name update

---

helpers/transitionReadinessData.js
pages/edit-milestone/EditMilestone.js
pages/edit-project/EditProject.js

- Fix rag roll up on overview page
- clear cache when editing project or milestone

fix rag roll ups

---

helpers/transitionReadinessData.js

Update to milestone tableau URL

Update to milestone tableau url

---

helpers/transitionReadinessData.js

- Dont map projects with NO milestones
- hide decommissioned milestones

Dont map projects with NO milestones & hide decommissioned milestones

---

common/macros/readiness-accordion.njk
helpers/transitionReadinessData.js
pages/theme/Theme.scss

Turn milestone rayg box blue when complete

Turn milestone rayg box blue when complete

---

pages/authentication/logout/Logout.js
services/jwt.js
test/unit/pages/authentication/Logout.test.js
test/unit/services/jwt.test.js

JWT cookie isn't cleared on logout.  
I believe adding the domain to the cookie options should fix the issue.   Worked locally fine without the change, so needs to be tested on staging.

DDB-844 - Fix logout issue

---

config/default.json
helpers/transitionReadinessData.js
pages/data-entry-entity/entity-submission-success/EntitySubmissionSuccess.js
pages/edit-milestone/EditMilestone.js
pages/edit-project/EditProject.js
services/cache.js
services/redis.js
test/unit/pages/data-entry-entity/EntitySubmissionSuccess.test.js

- create a feature for caching so we can turn this off easily 
- reset cache at midnight

cron for clearing cache

---

common/scss/main.scss
common/views/navigation.njk
config/default.json
helpers/rayg.js
package.json
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/MeasureEdit.scss
test/unit/helpers/rayg.test.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

The initial page for editing measure data.  Pulls through measure data and displays a simple table.

DDB-881 - simple measure data page

---

common/scss/main.scss
common/views/navigation.njk
config/default.json
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-list/MeasureList.html
pages/data-entry-entity/measure-list/MeasureList.js
test/unit/pages/data-entry-entity/MeasureList.test.js

@AhdabNasir This is the backend to support the frontend measures list

get all measures for user to edit

---

.eslintrc.json
common/macros/data-entry-content.njk
config/development.json
helpers/parse.js
helpers/utils.js
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/MeasureEdit.scss
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Allows a user to add new measures data if they have the correct permissions
Measures listed and grouped date and filter
Upon submission, copies the lastest entry and creates new entries in the database
Has some simple data validation on the form data and also more in-depth validation on the entity objects to prevent incomplete / mismatch of data types
Temp frontend whilst other story is being worked on

DDB 884 - Add data entires backend

---

common/scss/main.scss
common/views/navigation.njk
config/default.json
config/production.json
models/entity.js
pages/data-entry-entity/measure-group/MeasureGroup.html
pages/data-entry-entity/measure-group/MeasureGroup.js
pages/data-entry-entity/measure-group/partials/edit.njk
pages/data-entry-entity/measure-group/partials/success.njk
pages/data-entry-entity/measure-list/MeasureList.html
pages/data-entry-entity/measure-list/MeasureList.js
pages/data-entry-entity/measure-list/MeasureList.scss
test/unit/mysql-mock.js
test/unit/pages/EditProject.test.js
test/unit/pages/admin/CategoryFieldList.test.js
test/unit/pages/admin/HeadlineMeasures.test.js
test/unit/pages/data-entry-entity/CategoryTemplate.test.js
test/unit/pages/data-entry-entity/EntityImport.test.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js
test/unit/pages/data-entry-entity/MeasureGroup.test.js
test/unit/pages/data-entry-entity/MeasureList.test.js
test/unit/pages/editMilestone.test.js

- update measure list to include groups
- add a group edit page

Measure group information

---

pages/admin/headline-measures/HeadlineMeasures.js

- remove empty items before looking for duplicates

Fix headline measure issues

---

common/macros/data-entry-content.njk
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/MeasureEdit.scss
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Measure upload page - changes based on design updates

Measure upload page - changes based on design updates

---

common/views/template.njk

By default it will be zoomed out

min width viewport

---

common/views/navigation.njk
pages/data-entry-entity/category-template/CategoryTemplate.js
pages/data-entry-entity/entity-bulk-upload/EntityBulkUpload.js
pages/data-entry-entity/entity-import/EntityImport.js
pages/data-entry-entity/entity-submission-success/EntitySubmissionSuccess.js
pages/data-entry-entity/measure-group/MeasureGroup.html
pages/data-entry-entity/measure-group/MeasureGroup.js
pages/data-entry-entity/measure-group/partials/edit.njk
test/unit/pages/data-entry-entity/CategoryTemplate.test.js
test/unit/pages/data-entry-entity/EntityBulkUpload.test.js
test/unit/pages/data-entry-entity/EntityImport.test.js
test/unit/pages/data-entry-entity/EntitySubmissionSuccess.test.js
test/unit/pages/data-entry-entity/MeasureGroup.test.js

- group rayg status now configures by drop-down & no comment only option for groups
- move entity bulk upload to the admin section

Edit measure group update

---

helpers/transitionReadinessData.js
services/cache.js

only append measure values if the measure is the only measure in the group and there are no filter values

update measure append value

---

pages/admin/headline-measures/HeadlineMeasures.html
pages/admin/headline-measures/HeadlineMeasures.js
test/unit/pages/admin/HeadlineMeasures.test.js

- Append theme to measures
- Sort alphabetically

headline figures update

---

common/macros/data-entry-content.njk
common/macros/measure-information.njk
core/pages/page.js
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/partials/forms.njk
pages/data-entry-entity/measure-edit/partials/success.njk
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Allow users to update measure information

DDB 893 - Update measure information

---

pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/MeasureEdit.scss
pages/data-entry-entity/measure-edit/partials/forms.njk
pages/data-entry-entity/measure-group/MeasureGroup.html

- show group details in edit measure
- use rayg row status

show group details in edit measure, use rayg row status

---

common/macros/measure-information.njk
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/partials/forms.njk
pages/data-entry-entity/measure-edit/partials/success.njk
pages/data-entry-entity/measure-group/partials/success.njk
test/unit/pages/data-entry-entity/MeasureEdit.test.js

When a measure is not in a group and has no filter value
Update rayg row when adding a new value
When editing thresholds update rayg row
Hide overall dropdown

DBB 992 - allow appended values

---

pages/theme/Theme.scss

fix rag position - bug

---

core/pages/page.js

Bug raised from Simon and wants this deployed today

fix time remaining

---

common/macros/measure-information.njk
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js

Fixed broken upload form style

---

pages/data-entry-entity/measure-edit/MeasureEdit.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

fix for multiple rays rows for measure edit

fix for multiple rays rows for measure edit

---

pages/data-entry-entity/measure-edit/MeasureEdit.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Only update RAYG row when a date is newer than the current entires
Also added logic to prevent data being add to an existing date

Only update RAYG row when the entered date is newer than the current entires

---

pages/data-entry-entity/measure-edit/MeasureEdit.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Ensure we update group description field when the name field is updated for the RAYG row.  This is so it appears correctly on the overview theme page

Measure upload - update group description

---

common/macros/data-entry-content.njk
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/partials/forms.njk

Allow a user to update the rayg value when measure contains dates in the future

Measure upload - dates in the future

---

.secrets.baseline
config/default.json
helpers/filterMetrics.js
migrations/21_user_metrics.js
models/user.js
models/userMetric.js
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-group/MeasureGroup.js
pages/data-entry-entity/measure-list/MeasureList.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js
test/unit/pages/data-entry-entity/MeasureGroup.test.js
test/unit/pages/data-entry-entity/MeasureList.test.js

Script to create user_metrics coming

Measure permissions

---

pages/data-entry-entity/measure-edit/MeasureEdit.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

allow partial entries for measure where filters are used

Measure upload = allow partial entries for measure where filters are used

---

pages/data-entry-entity/measure-edit/MeasureEdit.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js

Update for user permissions for edit page for Get and Post request

Update for user permissions for edit page

---

common/macros/data-entry-content.njk
config/default.json
config/production.json
pages/data-entry-entity/measure-edit/partials/forms.njk
pages/data-entry-entity/measure-list/MeasureList.js
pages/data-entry-entity/measure-value/MeasureValue.js

Removed edit links and disabled edit measure value page.

Enable measure upload for production. 

---

common/views/navigation.njk
config/default.json
config/development.json
pages/admin/user-management/authentication/UserManagementAuthentication.js
pages/admin/user-management/create-user/CreateUser.html
pages/admin/user-management/create-user/CreateUser.js
pages/admin/user-management/create-user/partials/form.html
pages/admin/user-management/create-user/partials/success.html
pages/admin/user-management/list/UserManagementList.html
services/notify.js
test/unit/pages/admin/UserManagementAuthentication.test.js
test/unit/pages/admin/UserManagementCreateUser.test.js
test/unit/services/notify.test.js

* Create User Form page
** Validates if user already exists
** validates for required fields (roles/departments)
** Sends email notification on successful creation
* Create User confirmation page
* "Create User" button on Manage-users-list page
* create a `notify` service which handles sending email with temp password
** update `pages/admin/user-management/authentication/UserManagementAuthentication.js` to use this new service
* Unit tests

DDB-499: create user

---

common/macros/data-entry-content.njk
common/macros/measure-heading.njk
common/macros/measure-value.njk
common/scss/main.scss
common/views/navigation.njk
helpers/measures.js
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-edit/MeasureEdit.scss
pages/data-entry-entity/measure-edit/partials/forms.njk
pages/data-entry-entity/measure-value/MeasureValue.html
pages/data-entry-entity/measure-value/MeasureValue.js
pages/data-entry-entity/measure-value/MeasureValue.scss
test/unit/helpers/measures.test.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js
test/unit/pages/data-entry-entity/MeasureValue.test.js

Measure upload edit values backend
Includes frontend changes and backend work to populate form data
Still work in process to save data

Measure upload edit values backend

---

migrations/22_entity_updated_at.js
models/entity.js
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-group/MeasureGroup.js
test/unit/models/entity.test.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js
test/unit/pages/data-entry-entity/MeasureGroup.test.js

At updated_at to the entity table
Only update the field when data is added via the new upload admin panel
On migration set new column to null

Add updated_at to entity table

---

common/macros/data-entry-content.njk
common/macros/measure-value.njk
helpers/measures.js
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-value/MeasureValue.html
pages/data-entry-entity/measure-value/MeasureValue.js
test/unit/helpers/measures.test.js
test/unit/pages/data-entry-entity/MeasureEdit.test.js
test/unit/pages/data-entry-entity/MeasureValue.test.js

Allow users to update existing measure values

DDB-1021 - Measure upload - edit existing values

---

helpers/measures.js
pages/data-entry-entity/measure-edit/MeasureEdit.js
pages/data-entry-entity/measure-value/MeasureValue.js
test/unit/helpers/measures.test.js

Addressing a minor PR to remove a duplicate function

Measure upload - edit value PR comment

---

common/macros/data-entry-content.njk
models/entity.js
pages/data-entry-entity/measure-value/MeasureValue.html
pages/data-entry-entity/measure-value/MeasureValue.js
pages/data-entry-entity/measure-value/MeasureValue.scss
pages/data-entry-entity/measure-value/partials/delete-success.njk
pages/data-entry-entity/measure-value/partials/delete-value.njk
pages/data-entry-entity/measure-value/partials/edit-value.njk
test/unit/models/entity.test.js
test/unit/pages/data-entry-entity/MeasureValue.test.js

Allow a user to delete measure value(s)
update RAYG row when the latest measure value is deleted for a single measure in the group with no filters
Don't allow a user to delete a value when only one date for the measure

DDB-1022 - Measure update - delete values

---

pages/admin/user-management/create-user/CreateUser.js
test/unit/pages/admin/UserManagementCreateUser.test.js

* Fix an issue in user creation where instead of temp password, hash of temp password was sent in email

Send temp password in email

---

.gitignore
common/scss/main.scss
common/views/feedback.njk
common/views/navigation.njk
common/views/template.njk
config/custom-environment-variables.json
config/default.json
middleware/ipWhitelist.js
migrations/22_static_roles.js
models/user.js
package-lock.json
package.json
pages/authentication/login/Login.js
pages/readiness-overview/ReadinessOverview.js
pages/start/Start.js
pages/tableau-export/TableauExport.js
pages/theme/Theme.js
scripts/staticSiteGenerator.js
services/authentication.js
services/cache.js
test/unit/middleware/ipWhitelist.test.js
test/unit/pages/ReadinessOverview.test.js
test/unit/pages/Start.test.js
test/unit/pages/Theme.test.js
test/unit/pages/authentication/Login.test.js
test/unit/services/authentication.test.js

- update header for govuk design
- add two new roles: static and skip_2fa
- if user has skip_2fa role and ip is whitelisted skip 2fa auth
- add static site export script
- use node cache if no redis url

Static export

---

config/production.json

Enable measure values editing / deleting page on prod.  This is already in prod.

Enabled measure values editing / deleting page on prod

---

notifications/updatedMeasures.js
test/unit/notifications/updatedMeasures.test.js

* Send list of message for better formatting

Ddb 1096 notification of updates to measures

---

common/scss/small-device.scss
pages/admin/category-field-list/CategoryFieldList.html
pages/admin/edit-category-field/EditCategoryField.html
pages/admin/edit-project-field/EditProjectField.html
pages/admin/user-management/authentication/UserManagementAuthentication.html
pages/admin/user-management/create-user/CreateUser.html
pages/data-entry-entity/entity-bulk-upload/EntityBulkUpload.html
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-group/MeasureGroup.html
pages/data-entry/bulk-upload/BulkUpload.html
pages/edit-milestone/EditMilestone.html
pages/edit-project/EditProject.html
pages/impact-definitions/ImpactDefinitions.html
pages/milestone-details/MilestoneDetails.html
pages/project-details/ProjectDetails.html
pages/rayg-definitions/RaygDefinitions.html
pages/theme/Theme.html

- Also a bug fix which now allows the back button to work on safari

Theme mobile responsive updates

---

config/development.json
pages/rayg-definitions/RaygDefinitions.js
scripts/staticSiteGenerator.js
staging.yml
test/unit/pages/RaygDefinitions.test.js

- increase staging memory
- add da and static role to rayg definition page
- fix login url for static export

static export and da role fixes

---

common/scss/small-device.scss
pages/readiness-overview/ReadinessOverview.scss

- Breakpoint size change now `@media only screen and (max-width:840px)`
- Word wrap on overview blocks

Breakpoint size change and word wrap

---

pages/data-entry-entity/measure-group/MeasureGroup.js
test/unit/pages/data-entry-entity/MeasureGroup.test.js

Bug fix - when updating group description ensure we also update the name field

DDB-1312 - Bug fix for updating group description 

---

common/macros/readiness-theme-card.njk
common/views/template.njk
pages/readiness-overview/ReadinessOverview.html
pages/readiness-overview/ReadinessOverview.scss
pages/theme/Theme.html

Update H tags
Headline figures and theme cards now have focus state on keyboard/screenreader navigation
Updated page titles

DDB-1272 - Overview accessibility changes

---

common/macros/attribute.njk
common/macros/readiness-accordion.njk
common/views/template.njk
middleware/webpack.js
package-lock.json
package.json
pages/theme/Theme.html
pages/theme/Theme.scss
webpack.config.js

- Polyfil for forEach and includes
- Link should not wrap all content for items in first column, moved link onto title, added css to make block clickable
- Active/focus state on measures, projects, statements etc
- Active item now have aria-current=“page”
- Hide arrow from screen reader
- Tableau iframe - ensure title attribute is set

Theme page accessible

---

middleware/entityUserPermissions.js
pages/tableau-export/TableauExport.js
test/unit/pages/TableauExport.test.js

- add new query param "role" that allows to filter data by a specific role

wdc static

---

common/views/template.njk

Hide privacy policy for the static site

DDB-1331- Hide privacy policy on static site

---

common/macros/readiness-accordion.njk
common/macros/searchMeasures.njk
pages/theme/Theme.html
pages/theme/Theme.scss

- Fixed aria broken tags
- Accessibility fixes on search
- Margin fixes
- Missing H3 content fix
- Contrast colour fix based on Cervens new designs

Theme accessibility fixes

---

common/scss/search-measures.scss

Added keyboard focus state to search buttons

Added keyboard focus state to search buttons

---

common/javascript/search.js
common/macros/searchMeasures.njk
common/scss/search-measures.scss
helpers/measures.js
pages/search-transition-readiness/SearchTransitionReadiness.html
pages/search-transition-readiness/SearchTransitionReadiness.scss
scripts/staticSiteGenerator.js

- fix search width
- fix search on static site
- fix cannot search items with %
- show number of results

search bug fixes

---

common/scss/small-device.scss
common/views/template.njk
config/default.json
pages/accessibility/Accessibility.html
pages/accessibility/Accessibility.js
test/unit/pages/Accessibility.test.js

Took relevant content from the Accessibility Coronavirus page

Accessibility page

---

pages/all-data/partials/filters/checkboxes.njk

Fixed bug where clicking on any label always selects the first checkbox, this is now fixed

Unique id for each checkbox

---

common/javascript/main.js
common/javascript/readiness-accordion.js
pages/project-details/ProjectDetails.html

dont clear accordion state on view project details, dont show more than one project details at a time

fixes for project details

---

common/scss/main.scss
pages/rayg-definitions/RaygDefinitions.html

Fixed logo focus state. Moved aria tags on RAYG page.

Minor style and accessibility fix

---

helpers/transitionReadinessData.js

Milestones which were hidden (ie Decommissioned completion state) were showing up as blank rows.  This solves that.

DDB-1422 don't show hidden milestones as blank entries

---

pages/missed-milestones/MissedMilestones.html
pages/missed-milestones/MissedMilestones.js
test/unit/pages/MissedMilestones.test.js

- A request from Simon to remove department BPDG from Missed Milestones graph

Remove BPDG from graph

---

common/macros/readiness-theme-card.njk
common/scss/main.scss
pages/readiness-overview/ReadinessOverview.html
pages/readiness-overview/ReadinessOverview.scss

- Only 1 link per block
- Hover state on active blocks

UI updates to overview

---

models/milestone.js
pages/data-entry/import/Import.js
pages/data-entry/project-milestone-template/ProjectMilestoneTemplate.js
test/unit/models/milestone.test.js

fixes https://technologyprogramme.atlassian.net/browse/DDB-1230

no custom milestone id

---

pages/tableau-export/TableauExport.js
test/unit/pages/TableauExport.test.js

- revert hard coded schema
- add logs for schema and data tableau export

tableau export logs

---

migrations/27_daily_notifications_lock.js
migrations/28_add_tagging_tables.js
models/entity.js
models/tag.js
models/tagEntity.js
test/unit/models/entity.test.js
test/unit/models/tag.test.js
test/unit/models/tagEntity.test.js

Tagging table

---

common/javascript/readiness-accordion.js

fix https://technologyprogramme.atlassian.net/browse/DDB-1502

fix console error when expanding and closing projects in transition overview

---

common/scss/small-device.scss
pages/rayg-definitions/RaygDefinitions.html
pages/rayg-definitions/RaygDefinitions.scss
pages/readiness-overview/ReadinessOverview.html

- Also includes minor changes for mobile responsive

Replace icons with images on RAG page

---

common/macros/readiness-theme-card.njk
pages/readiness-overview/ReadinessOverview.html
pages/theme/Theme.html
pages/theme/Theme.scss

- Aria labels on link
- Indentation on accordion

accessibility changes

---

common/macros/status.njk
common/scss/main.scss
pages/rayg-definitions/RaygDefinitions.html
pages/readiness-overview/ReadinessOverview.html

Copy changes based on Cervens designs

Copy changes

---

pages/tableau-export/TableauExport.js
test/unit/pages/TableauExport.test.js

DDB-1509- Adding last updated to WDC export

DDB-1509- Adding last updated to WDC export

---

common/macros/active-statement-box.njk
common/scss/small-device.scss
pages/theme/Theme.html

Minor UI styles for mobile site
Updated back-link text
created macro for a reuseable selected outcome block

Minor UI changes

---

helpers/measures.js
pages/search-transition-readiness/SearchTransitionReadiness.html
pages/search-transition-readiness/SearchTransitionReadiness.scss
pages/search-transition-readiness/partials/colorFilters.njk
test/unit/helpers/measures.test.js

Updated search page to include new design for RAYG status

Search page RAYG design update

---

common/javascript/readiness-accordion.js
common/macros/readiness-accordion.njk
helpers/measures.js
helpers/transitionReadinessData.js
pages/search-transition-readiness/SearchTransitionReadiness.html
pages/theme/Theme.html

- projects have own link on transition readiness pages
- allow projects to be searchable

allow projects to be searchable

---

pages/readiness-overview/ReadinessOverview.html

Updated text on the overview page

Updated text on the overview page

---

services/sequelize.js
test/unit/services/sequelize.test.js

- enable logging for sequelise
- enable connection pool for sequelise

WDC potential fix

---

pages/tableau-export/TableauExport.js
services/logger.js

- also a few more logs in tableau exports

add headers to logs

---

config/default.json
config/production.json
config/staging.json
helpers/measures.js
helpers/transitionReadinessData.js
services/sequelize.js
test/unit/services/sequelize.test.js

- db logs only staging and prod
- fix some entities without rayg rollups

db logs only staging and prod, fix some entities without rayg rollups

---

common/views/navigation.njk
config/default.json
pages/admin/tag-management/delete/DeleteTag.html
pages/admin/tag-management/delete/DeleteTag.js
pages/admin/tag-management/list/TagManagementList.html
pages/admin/tag-management/list/TagManagementList.js
test/unit/pages/admin/DeleteTag.test.js
test/unit/pages/admin/TagManagementList.test.js

- add link to delete tag from tag list
- add delete tag page

add delete tag page

---

common/views/navigation.njk

DDB 1617 - Fixed missing menu on edit user

DDB 1617 - Fixed missing menu on edit user

---

helpers/transitionReadinessData.js

- update groupById function so that it finds any entities with property
- update sortById function so that it filters items with the given property

DDB-1586 - fix comms links on search page

---

config/default.json
pages/admin/user-management/edit-user/partials/form.html
pages/admin/user-management/reset-user-2fa/ResetUser2FA.html
pages/admin/user-management/reset-user-2fa/ResetUser2FA.js
test/unit/pages/admin/UserManagementResetUser2FA.test.js

DDB-1524 - Reset user 2FA

---

common/views/navigation.njk

Fixed missing navigation and selected elements for user management

User management navigation fix

---

config/default.json
migrations/29_user_is_active.js
models/user.js
pages/admin/user-management/deactivate/DeactivateUser.html
pages/admin/user-management/deactivate/DeactivateUser.js
pages/admin/user-management/edit-user/partials/form.html
pages/admin/user-management/list/UserManagementList.html
services/authentication.js
test/unit/models/user.test.js
test/unit/pages/admin/UserManagementDeactivateUser.test.js
test/unit/services/authentication.test.js

- add new page to allow admin to deactivate user
- dont allow user to login if they are not active

add deactivate user page

---

helpers/entity.js
middleware/entityUserPermissions.js
pages/tableau-export/TableauExport.js
test/unit/helpers/entity.test.js
test/unit/middleware/entityUserPermissions.test.js
test/unit/pages/TableauExport.test.js

- add new entity helper
- implement it with entity permissions

DDB-1642 - Permissions - create a reusable object to generate entity parent/child data

---

pages/theme/Theme.scss

position sticky to work in safari

---

common/views/navigation.njk
config/default.json
helpers/entity.js
middleware/entityUserPermissions.js
pages/admin/entity-list/EntityList.html
pages/admin/entity-list/EntityList.js
pages/tableau-export/TableauExport.js
test/unit/helpers/entity.test.js
test/unit/pages/admin/EntityList.test.js

- Add new page to show categories then entities within those categories
- Extend helpers/entity to return path to each entity
- Extend helpers/entity to also add fields for each entity
Todo:
- cover with tests

DDB-1529 - Entities - List page for all entities types

---

test/cypress/integration/Admin/TS_Admin_01_Managetags.js
test/cypress/integration/HMGDelivery/TS_HMG_01_VerifyAllDepartment.js
test/cypress/integration/HMGDelivery/TS_HMG_02_VerifyProjectByDept.js
test/cypress/integration/HMGDelivery/TS_HMG_03_VerifyAllMilestones.js
test/cypress/integration/HMGDelivery/TS_HMG_04_VerifyMilestonesByDept.js
test/cypress/integration/HMGDelivery/TS_HMG_05_Verify_ShowHide_Filter.js
test/cypress/integration/HMGDelivery/TS_HMG_06_Verify_Apply_Clearall_Filter.js
test/cypress/integration/Userflow/TS01_Admin_Workflow.js
test/cypress/integration/Userflow/TS02_Uploader_Workflow.js
test/cypress/integration/Userflow/TS03_Management_Workflow.js
test/cypress/integration/Userflow/TS04_ManagementOverview_Workflow.js
test/cypress/integration/Userflow/TS05_DA_Workflow.js
test/cypress/pages/Admin.js
test/cypress/pages/Filters.js
test/cypress/pages/HMGDelivery.js
test/cypress/pages/Login.js
test/cypress/pages/Navigation.js
test/cypress/plugins/index.js
test/cypress/support/db_project.js
test/cypress/support/db_user.js
test/cypress/support/index.js

1. Updated naming standards for constants.
2. Replaced 'var' with 'let'.
3. Prefixed scenario description with test script name

Updated naming standards.

---

common/views/navigation.njk

Hide manage entity list nav on prod

Hide manage entity list nav on prod

---

pages/admin/entities/entity-remap/EntityRemap.js
pages/admin/entities/entity-remap/partials/table.html
test/unit/pages/admin/EntityRemap.test.js

DDB 1737 - remap entity - populate current selected

DDB 1737 - remap entity - populate current selected

---

pages/admin/category-list/CategoryList.html
pages/admin/entities/entity-list/EntityList.html
pages/admin/entities/entity-list/EntityList.js
pages/admin/permissions/Permissions.scss
pages/admin/project-field-list/ProjectFieldList.html
pages/admin/rayg-values/RaygValues.html
pages/admin/tag-management/list/TagManagementList.html
pages/admin/user-management/authentication/partials/reset.html
pages/admin/user-management/list/UserManagementList.html
pages/admin/user-management/reset-user-2fa/ResetUser2FA.html
pages/all-data/AllData.scss
pages/data-entry-entity/measure-group/partials/edit.njk
pages/search-transition-readiness/SearchTransitionReadiness.html
test/unit/pages/admin/EntityList.test.js

The following UI updates have been made to make it consistent throughout dashboard - 
- Active states for category on Permissions and Manage Entities page
- Edit/Delete/View links on a table to be on the far right
- Naming, border fixes and display changes for project field page
- Bold theme titles for rayg values page
- Reduce checkbox items gap
- Titles should be large rather than x-large

Admin UI Updates

---

pages/admin/entities/entity-remap/EntityRemap.js
pages/admin/entities/entity-remap/partials/table.njk
test/unit/pages/admin/EntityRemap.test.js

Change form input form as real data on staging was producing an error.

DDB-1738 - staging bug fix

---

helpers/roleEntity.js
pages/admin/permissions/Permissions.js
pages/admin/permissions/PermissionsTable.njk
test/unit/helpers/roleEntity.test.js

* Show hierarchies for entities in permissions
* DDB-1780 - fix

DDB-1746: UI improvements for permissions

---

common/views/navigation.njk
pages/admin/category-field-list/CategoryFieldList.html
pages/admin/edit-project-field/partials/field-success.njk
pages/admin/entities/entity-delete/EntityDelete.html
pages/admin/entities/entity-list/EntityList.html
pages/admin/entities/entity-remap/EntityRemap.html
pages/admin/permissions/Permissions.html
pages/admin/permissions/partial/success.html
pages/admin/project-field-list/ProjectFieldList.html
pages/admin/static-exports/StaticExports.html
pages/admin/tag-management/add/AddTag.html
pages/admin/tag-management/delete/DeleteTag.html
pages/admin/user-management/authentication/UserManagementAuthentication.html
pages/admin/user-management/deactivate/DeactivateUser.html
pages/admin/user-management/edit-user/EditUser.html
pages/admin/user-management/edit-user/partials/success.html
pages/admin/user-management/reset-user-2fa/ResetUser2FA.html
pages/data-entry-entity/entity-bulk-upload/EntityBulkUpload.html
pages/data-entry-entity/entity-import/EntityImport.html
pages/data-entry-entity/measure-delete/MeasureDelete.html
pages/data-entry-entity/measure-edit/MeasureEdit.html
pages/data-entry-entity/measure-group/MeasureGroup.html
pages/data-entry-entity/measure-list/MeasureList.html
pages/data-entry-entity/measure-value/MeasureValue.html
pages/data-entry/bulk-upload/BulkUpload.html
pages/data-entry/import/Import.html

- Approach for when back button and nav should be displayed accross dashboard as agreed by Cerven. Parent page to display the nav bar whereas child pages will display back button with exception of success screens and import screens
- Tables within Admin to be full width
- Minor text updates and design updates

Back button nav update and width changes

---

common/views/navigation.njk

Enabling manage entities nav prior to release

Enabling manage entities nav

---

common/macros/visualisations.njk

fixed milestone issue
